package syscall

type SyscallImplementation interface {
	Accept(fd int) (nfd int, sa Sockaddr, err error)
	Accept4(fd int, flags int) (nfd int, sa Sockaddr, err error)
	Access(path string, mode uint32) (err error)
	Acct(path string) (err error)
	Adjtimex(buf *Timex) (state int, err error)
	AttachLsf(fd int, i []SockFilter) error
	Bind(fd int, sa Sockaddr) (err error)
	BindToDevice(fd int, device string) (err error)
	Chdir(path string) (err error)
	Chmod(path string, mode uint32) (err error)
	Chown(path string, uid int, gid int) (err error)
	Chroot(path string) (err error)
	Clearenv()
	Close(fd int) (err error)
	CloseOnExec(fd int)
	CmsgLen(datalen int) int
	CmsgSpace(datalen int) int
	Connect(fd int, sa Sockaddr) (err error)
	Creat(path string, mode uint32) (fd int, err error)
	DetachLsf(fd int) error
	Dup(oldfd int) (fd int, err error)
	Dup2(oldfd int, newfd int) (err error)
	Dup3(oldfd int, newfd int, flags int) (err error)
	Environ() []string
	EpollCreate(size int) (fd int, err error)
	EpollCreate1(flag int) (fd int, err error)
	EpollCtl(epfd int, op int, fd int, event *EpollEvent) (err error)
	EpollWait(epfd int, events []EpollEvent, msec int) (n int, err error)
	Exec(argv0 string, argv []string, envv []string) (err error)
	Exit(code int)
	Faccessat(dirfd int, path string, mode uint32, flags int) (err error)
	Fallocate(fd int, mode uint32, off int64, len int64) (err error)
	Fchdir(fd int) (err error)
	Fchmod(fd int, mode uint32) (err error)
	Fchmodat(dirfd int, path string, mode uint32, flags int) (err error)
	Fchown(fd int, uid int, gid int) (err error)
	Fchownat(dirfd int, path string, uid int, gid int, flags int) (err error)
	FcntlFlock(fd uintptr, cmd int, lk *Flock_t) error
	Fdatasync(fd int) (err error)
	Flock(fd int, how int) (err error)
	ForkExec(argv0 string, argv []string, attr *ProcAttr) (pid int, err error)
	Fstat(fd int, stat *Stat_t) (err error)
	Fstatfs(fd int, buf *Statfs_t) (err error)
	Fsync(fd int) (err error)
	Ftruncate(fd int, length int64) (err error)
	Futimes(fd int, tv []Timeval) (err error)
	Futimesat(dirfd int, path string, tv []Timeval) (err error)
	Getcwd(buf []byte) (n int, err error)
	Getdents(fd int, buf []byte) (n int, err error)
	Getegid() (egid int)
	Getenv(key string) (value string, found bool)
	Geteuid() (euid int)
	Getgid() (gid int)
	Getgroups() (gids []int, err error)
	Getpagesize() int
	Getpgid(pid int) (pgid int, err error)
	Getpgrp() (pid int)
	Getpid() (pid int)
	Getppid() (ppid int)
	Getpriority(which int, who int) (prio int, err error)
	Getrlimit(resource int, rlim *Rlimit) (err error)
	Getrusage(who int, rusage *Rusage) (err error)
	GetsockoptInet4Addr(fd, level, opt int) (value [4]byte, err error)
	GetsockoptInt(fd, level, opt int) (value int, err error)
	Gettid() (tid int)
	Gettimeofday(tv *Timeval) (err error)
	Getuid() (uid int)
	Getwd() (wd string, err error)
	Getxattr(path string, attr string, dest []byte) (sz int, err error)
	InotifyAddWatch(fd int, pathname string, mask uint32) (watchdesc int, err error)
	InotifyInit() (fd int, err error)
	InotifyInit1(flags int) (fd int, err error)
	InotifyRmWatch(fd int, watchdesc uint32) (success int, err error)
	Ioperm(from int, num int, on int) (err error)
	Iopl(level int) (err error)
	Kill(pid int, sig Signal) (err error)
	Klogctl(typ int, buf []byte) (n int, err error)
	Lchown(path string, uid int, gid int) (err error)
	Link(oldpath string, newpath string) (err error)
	Listen(s int, n int) (err error)
	Listxattr(path string, dest []byte) (sz int, err error)
	LsfSocket(ifindex, proto int) (int, error)
	Lstat(path string, stat *Stat_t) (err error)
	Madvise(b []byte, advice int) (err error)
	Mkdir(path string, mode uint32) (err error)
	Mkdirat(dirfd int, path string, mode uint32) (err error)
	Mkfifo(path string, mode uint32) (err error)
	Mknod(path string, mode uint32, dev int) (err error)
	Mknodat(dirfd int, path string, mode uint32, dev int) (err error)
	Mlock(b []byte) (err error)
	Mlockall(flags int) (err error)
	Mmap(fd int, offset int64, length int, prot int, flags int) (data []byte, err error)
	Mount(source string, target string, fstype string, flags uintptr, data string) (err error)
	Mprotect(b []byte, prot int) (err error)
	Munlock(b []byte) (err error)
	Munlockall() (err error)
	Munmap(b []byte) (err error)
	Nanosleep(time *Timespec, leftover *Timespec) (err error)
	NetlinkRIB(proto, family int) ([]byte, error)
	Open(path string, mode int, perm uint32) (fd int, err error)
	Openat(dirfd int, path string, flags int, mode uint32) (fd int, err error)
	ParseDirent(buf []byte, max int, names []string) (consumed int, count int, newnames []string)
	ParseNetlinkMessage(b []byte) ([]NetlinkMessage, error)
	ParseNetlinkRouteAttr(m *NetlinkMessage) ([]NetlinkRouteAttr, error)
	ParseSocketControlMessage(b []byte) ([]SocketControlMessage, error)
	ParseUnixRights(m *SocketControlMessage) ([]int, error)
	Pause() (err error)
	Pipe(p []int) (err error)
	Pipe2(p []int, flags int) (err error)
	PivotRoot(newroot string, putold string) (err error)
	Pread(fd int, p []byte, offset int64) (n int, err error)
	PtraceAttach(pid int) (err error)
	PtraceCont(pid int, signal int) (err error)
	PtraceDetach(pid int) (err error)
	PtraceGetEventMsg(pid int) (msg uint, err error)
	PtraceGetRegs(pid int, regsout *PtraceRegs) (err error)
	PtracePeekData(pid int, addr uintptr, out []byte) (count int, err error)
	PtracePeekText(pid int, addr uintptr, out []byte) (count int, err error)
	PtracePokeData(pid int, addr uintptr, data []byte) (count int, err error)
	PtracePokeText(pid int, addr uintptr, data []byte) (count int, err error)
	PtraceSetOptions(pid int, options int) (err error)
	PtraceSetRegs(pid int, regs *PtraceRegs) (err error)
	PtraceSingleStep(pid int) (err error)
	PtraceSyscall(pid int, signal int) (err error)
	Pwrite(fd int, p []byte, offset int64) (n int, err error)
	RawSyscall(trap, a1, a2, a3 uintptr) (r1, r2 uintptr, err Errno)
	RawSyscall6(trap, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err Errno)
	Read(fd int, p []byte) (n int, err error)
	ReadDirent(fd int, buf []byte) (n int, err error)
	Readlink(path string, buf []byte) (n int, err error)
	Reboot(cmd int) (err error)
	Recvfrom(fd int, p []byte, flags int) (n int, from Sockaddr, err error)
	Recvmsg(fd int, p, oob []byte, flags int) (n, oobn int, recvflags int, from Sockaddr, err error)
	Removexattr(path string, attr string) (err error)
	Rename(oldpath string, newpath string) (err error)
	Renameat(olddirfd int, oldpath string, newdirfd int, newpath string) (err error)
	Rmdir(path string) (err error)
	Seek(fd int, offset int64, whence int) (off int64, err error)
	Select(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timeval) (n int, err error)
	Sendfile(outfd int, infd int, offset *int64, count int) (written int, err error)
	Sendmsg(fd int, p, oob []byte, to Sockaddr, flags int) (err error)
	SendmsgN(fd int, p, oob []byte, to Sockaddr, flags int) (n int, err error)
	Sendto(fd int, p []byte, flags int, to Sockaddr) (err error)
	SetLsfPromisc(name string, m bool) error
	SetNonblock(fd int, nonblocking bool) (err error)
	Setdomainname(p []byte) (err error)
	Setenv(key, value string) error
	Setfsgid(gid int) (err error)
	Setfsuid(uid int) (err error)
	Setgid(gid int) (err error)
	Setgroups(gids []int) (err error)
	Sethostname(p []byte) (err error)
	Setpgid(pid int, pgid int) (err error)
	Setpriority(which int, who int, prio int) (err error)
	Setregid(rgid int, egid int) (err error)
	Setresgid(rgid int, egid int, sgid int) (err error)
	Setresuid(ruid int, euid int, suid int) (err error)
	Setreuid(ruid int, euid int) (err error)
	Setrlimit(resource int, rlim *Rlimit) (err error)
	Setsid() (pid int, err error)
	SetsockoptByte(fd, level, opt int, value byte) (err error)
	SetsockoptICMPv6Filter(fd, level, opt int, filter *ICMPv6Filter) error
	SetsockoptIPMreq(fd, level, opt int, mreq *IPMreq) (err error)
	SetsockoptIPMreqn(fd, level, opt int, mreq *IPMreqn) (err error)
	SetsockoptIPv6Mreq(fd, level, opt int, mreq *IPv6Mreq) (err error)
	SetsockoptInet4Addr(fd, level, opt int, value [4]byte) (err error)
	SetsockoptInt(fd, level, opt int, value int) (err error)
	SetsockoptLinger(fd, level, opt int, l *Linger) (err error)
	SetsockoptString(fd, level, opt int, s string) (err error)
	SetsockoptTimeval(fd, level, opt int, tv *Timeval) (err error)
	Settimeofday(tv *Timeval) (err error)
	Setuid(uid int) (err error)
	Setxattr(path string, attr string, data []byte, flags int) (err error)
	Shutdown(fd int, how int) (err error)
	SlicePtrFromStrings(ss []string) ([]*byte, error)
	Socket(domain, typ, proto int) (fd int, err error)
	Socketpair(domain, typ, proto int) (fd [2]int, err error)
	Splice(rfd int, roff *int64, wfd int, woff *int64, len int, flags int) (n int64, err error)
	StartProcess(argv0 string, argv []string, attr *ProcAttr) (pid int, handle uintptr, err error)
	Stat(path string, stat *Stat_t) (err error)
	Statfs(path string, buf *Statfs_t) (err error)
	StringSlicePtr(ss []string) []*byte
	Symlink(oldpath string, newpath string) (err error)
	Sync()
	SyncFileRange(fd int, off int64, n int64, flags int) (err error)
	Syscall(trap, a1, a2, a3 uintptr) (r1, r2 uintptr, err Errno)
	Syscall6(trap, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err Errno)
	Sysinfo(info *Sysinfo_t) (err error)
	Tee(rfd int, wfd int, len int, flags int) (n int64, err error)
	Tgkill(tgid int, tid int, sig Signal) (err error)
	Times(tms *Tms) (ticks uintptr, err error)
	TimespecToNsec(ts Timespec) int64
	TimevalToNsec(tv Timeval) int64
	Truncate(path string, length int64) (err error)
	Umask(mask int) (oldmask int)
	Uname(buf *Utsname) (err error)
	UnixCredentials(ucred *Ucred) []byte
	UnixRights(fds ...int) []byte
	Unlink(path string) (err error)
	Unlinkat(dirfd int, path string) (err error)
	Unmount(target string, flags int) (err error)
	Unsetenv(key string) (err error)
	Unshare(flags int) (err error)
	Ustat(dev int, ubuf *Ustat_t) (err error)
	Utime(path string, buf *Utimbuf) (err error)
	Utimes(path string, tv []Timeval) (err error)
	UtimesNano(path string, ts []Timespec) (err error)
	Wait4(pid int, wstatus *WaitStatus, options int, rusage *Rusage) (wpid int, err error)
	Write(fd int, p []byte) (n int, err error)

	GetsockoptICMPv6Filter(fd, level, opt int) (*ICMPv6Filter, error)
	GetsockoptIPMreq(fd, level, opt int) (*IPMreq, error)
	GetsockoptIPMreqn(fd, level, opt int) (*IPMreqn, error)
	GetsockoptIPv6MTUInfo(fd, level, opt int) (*IPv6MTUInfo, error)
	GetsockoptIPv6Mreq(fd, level, opt int) (*IPv6Mreq, error)
	LsfJump(code, k, jt, jf int) *SockFilter
	LsfStmt(code, k int) *SockFilter
	Getpeername(fd int) (sa Sockaddr, err error)
	Getsockname(fd int) (sa Sockaddr, err error)
	Time(t *Time_t) (tt Time_t, err error)
	NsecToTimespec(nsec int64) (ts Timespec)
	NsecToTimeval(nsec int64) (tv Timeval)
	GetsockoptUcred(fd, level, opt int) (*Ucred, error)
	ParseUnixCredentials(m *SocketControlMessage) (*Ucred, error)

	SetReadDeadline(fd int, t int64) error
	SetWriteDeadline(fd int, t int64) error
	StopIO(fd int) error
}
